#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi
source "$PLUGIN_BASE_PATH/common/functions"

case "$1" in
  nginx:cache:enable)
		verify_app_name "$2"

    APP="$2"
    NGINX_CONF=$DOKKU_ROOT/$APP/nginx.conf.d/nginx-cache.conf
    NGINX_GLOBAL_CONF=/etc/nginx/conf.d/dokku-nginx-cache.conf

    rm -rf $NGINX_GLOBAL_CONF
    cat >$NGINX_GLOBAL_CONF <<EOL
proxy_cache_path /tmp/nginx levels:1-2 keys_zone=dokku:10m inactive=60m use_temp_path=off;
proxy_cache_key \$scheme\$request_method\$host\$request_uri;
EOL

    rm -rf $NGINX_CONF
    echo "proxy_cache dokku;" > NGINX_CONF
		echo "Enabled nginx proxy cache for $APP"

    dokku_log_info1 "Restarting app $APP"
    dokku ps:restart "$APP"
		;;

	nginx:cache:disable)
		verify_app_name "$2"

    APP="$2"
    NGINX_CONF=$DOKKU_ROOT/$APP/nginx.conf.d/nginx-cache.conf

		rm -rf $NGINX_CONF
		echo "Disabled nginx proxy cache for $APP"

    dokku_log_info1 "Restarting app $APP"
    dokku ps:restart "$APP"
		;;

  help | nginx:cache:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<help_content
    nginx:cache:enable <app>, Enable nginx proxy cache for <app>
    nginx:cache:disable <app>, Disable nginx proxy cache for <app>
help_content
    }

    if [[ $1 = "nginx:cache:help" ]] ; then
        echo -e 'Usage: dokku nginx:cache:[enable|disable] <app>'
        echo ''
        echo 'Toggle nginx proxy cache.'
        echo ''
        echo 'Commands:'
        help_content_func | sort | column -c2 -t -s,
    else
        help_content_func
    fi
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
