#!/usr/bin/env bash
# Cleanup up extra containers created

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN="$1"

if [[ "$PLUGIN" != "dokku-nginx-cache" ]]; then
  exit 0
fi

# Creating directory cache
mkdir -p /var/cache/nginx

cat > /etc/nginx/conf.d/dokku-cache.conf << EOF
#####
## INSTALLED BY DOKKU PLUGIN.
## Please visit https://github.com/koalalorenzo/dokku-nginx-cache for more info
####
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=dokku:10m max_size=2g inactive=60m use_temp_path=off;

EOF