#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

plugin-install() {
  # Creating directory cache
  mkdir -p /var/cache/nginx

  dokku_log_info1 "Adding cache configuration in NGINX settings directory"
  cat > /etc/nginx/conf.d/dokku-cache.conf << EOF
  #####
  ## INSTALLED BY DOKKU PLUGIN.
  ## Please visit https://github.com/kvandake/dokku-nginx-cache for more info
  ####
  add_header X-Cache-Status \$upstream_cache_status;

EOF

  cat > /etc/nginx/nginx.conf << EOF
  #####
  ## INSTALLED BY DOKKU PLUGIN.
  ## Please visit https://github.com/kvandake/dokku-nginx-cache for more info
  ####
  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=dokku:10m inactive=60m use_temp_path=off;

EOF

  chmod 0440 "/etc/nginx/conf.d/dokku-cache.conf"
}

plugin-install "$@"
