#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP=$1

# Exit if nginx-cache is not enabled for this app
if [[ ! -e $DOKKU_ROOT/$APP/NGINX_PROXY_CACHE ]]; then
  exit 0
fi

function add_setting_upstream {
  sed -i -r "s/upstream.*$/\0\n  $1/g" $DOKKU_ROOT/$APP/nginx.conf
}

function add_setting_location {
  sed -i -r "s/proxy_pass.*$/\0\n    $1/g" $DOKKU_ROOT/$APP/nginx.conf
}

add_setting_location "proxy_cache_key \$scheme\$request_method\$host\$request_uri;"

add_setting_location "proxy_cache dokku;"
add_setting_location "proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;"
