#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

nginx_cache_enable() {
  declare desc="Enable the cache for a specific app"
  local cmd="nginx-cache:enable"

  # Support --app/$DOKKU_APP_NAME flag by reordering args into "$cmd $DOKKU_APP_NAME $@"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  verify_app_name "$2"
  local APP="$2"

  dokku_log_info1 "Enabling NGINX proxy cache for $APP"
  touch $DOKKU_ROOT/$APP/NGINX_PROXY_CACHE

  dokku_log_info1 "Rebuilding nginx config for $APP"
  dokku nginx:build-config "$APP"
}

nginx_cache_enable "$@"
